import { Button, Flex, Stack } from '@chakra-ui/react'

import Head from 'next/head'
import {
	SubmitHandler,
	useForm,
	useFormState,
} from 'react-hook-form'
import { Input } from '../components/Form/Input'

type FormValues = {
	email: string
	password: string
}

export default function SignIn() {
	const { register, handleSubmit, formState } =
		useForm<FormValues>()

	const handleSignIn: SubmitHandler<FormValues> =
		async values => {
			await new Promise(resolve =>
				setTimeout(resolve, 2000)
			)
			console.log(values)
		}

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Flex
				w='100vw'
				h='100vh'
				align='center'
				justify='center'
			>
				<Flex
					as='form'
					w='100%'
					maxW={360}
					bg='gray.800'
					p='8'
					borderRadius={8}
					flexDirection='column'
					onSubmit={handleSubmit(handleSignIn)}
				>
					<Stack spacing='4'>
						<Input
							{...register('email')}
							type='email'
							label='E-mail'
							focusBorderColor='pink.500'
							bgColor='gray.900'
							variant='filled'
							_hover={{ bgColor: 'gray.900' }}
							size='lg'
						></Input>

						<Input
							{...register('password')}
							type='password'
							label='password'
							focusBorderColor='pink.500'
							bgColor='gray.900'
							variant='filled'
							_hover={{ bgColor: 'gray.900' }}
							size='lg'
						></Input>

						<Button
							type='submit'
							mt='6'
							colorScheme='pink'
							size='lg'
							isLoading={formState.isSubmitting}
						>
							Entrar
						</Button>
					</Stack>
				</Flex>
			</Flex>
		</>
	)
}
