import { Button, Flex, Stack } from '@chakra-ui/react'

import Head from 'next/head'
import { Input } from '../components/Form/Input'

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta
					name="description"
					content="Generated by create next app"
				/>
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Flex
				w="100vw"
				h="100vh"
				align="center"
				justify="center"
			>
				<Flex
					as="form"
					w="100%"
					maxW={360}
					bg="gray.800"
					p="8"
					borderRadius={8}
					flexDirection="column"
				>
					<Stack spacing="4">
						<Input
							name="email"
							type="email"
							label="E-mail"
							focusBorderColor="pink.500"
							bgColor="gray.900"
							variant="filled"
							_hover={{ bgColor: 'gray.900' }}
							size="lg"
						></Input>

						<Input
							name="password"
							type="password"
							label="password"
							focusBorderColor="pink.500"
							bgColor="gray.900"
							variant="filled"
							_hover={{ bgColor: 'gray.900' }}
							size="lg"
						></Input>

						<Button
							type="submit"
							mt="6"
							colorScheme="pink"
							size="lg"
						>
							Entrar
						</Button>
					</Stack>
				</Flex>
			</Flex>
		</>
	)
}
